name: Python CLI Calculator CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests with coverage
      run: |
        # Run pytest, measure coverage on the 'app' directory, and generate a report
        pytest --cov=app --cov-report=term-missing tests/
        
    - name: Check 100% coverage compliance
      # The coverage report command fails (exits non-zero) if coverage is below 100%
      run: |
        coverage report --fail-under=100
